### ISSUE TITLE
Can't build android with with RN 0.60

### ISSUE THREAD

**Issue by alfiedouglas0** [react-native-google-cast/react-native-google-cast#131]
Everytime I build the android project I get the error:

    FAILURE: Build failed with an exception.

    * What went wrong:
    Execution failed for task ':react-native-google- cast:compileDebugJavaWithJavac'.
    > Compilation failed; see the compiler error output for details. 

where the first error is:

    Error: Command failed: ./gradlew app:installDebug -PreactNativeDevServerPort=8081
    /Users/../GoogleCastActivity.java:14: error: package android.support.v7.app does not exist
    import android.support.v7.app.AppCompatActivity;

Its been driving me absolutley insnane, I've also added an issue on the reposity [here](https://github.com/react-native-google-cast/react-native-google-cast/issues/131) a couple days ago.

Things that I have tried:

 - Adding `implementation 'com.android.support:appcompat-v7:+'` to the build.gradle file which is suggested in a lot of SO posts that mention `error: package android.support.v7.app does not exist`
 - Installing on projects with different versions of react native - Installing it on RN0.57 worked perfectly but I am trying to install it on RN0.60 as some of the other packages I plan on using require a newer version of reactnative
 - Completed their installion guide in their README.md on their github a fair few times and gone through their troubleshooting section
  - The trouble shooting section of their [v4 branch]( https://github.com/react-native-google-cast/react-native-google-cast/tree/v4#troubleshooting) mentions: 
    

  > Android: If you're having version conflicts of the appcompat (or
  > google play services) libraries, make sure you set versions globally
  > in your project's top-level build.gradle:
> 
>     buildscript {   
>       ext {
>         buildToolsVersion = '27.0.3'
>         minSdkVersion = 16
>         compileSdkVersion = 27
>         targetSdkVersion = 26
>         supportLibVersion = '26.1.0'
>         castFrameworkVersion = '16.1.2'   }
>     ... }
  
  But I had no luck with trying that

These are the versions I am using:

    "react": "16.8.6",
    "react-native": "0.60.3",
    "react-native-google-cast": "^3.1.3"

Please let me know if there is any other relevant information I have missed, any help is greatly greatly appreciated!!

**Comment by flexgrip** [comment]
I'm having the same issue. Same exact versions as you @alfiedouglas0.

Any luck?

**Comment by alfiedouglas0** [comment]
> I'm having the same issue. Same exact versions as you @alfiedouglas0.
> 
> Any luck?

Nothing yet - lost waaay too much time trying to solve it so I've just decided to continue my project using RN0.57.

I've put a question on SO and I'll post here if I find anything out!

**Comment by flexgrip** [comment]
I kind of made some headway. The package builds, but now I get an error `Native module RNGoogleCast tried to override GoogleCastModule...`

I checked and I don't have the package listed twice. So I can't figure out what's going on. 

How did you downgrade to RN0.57? Any problems?

**Comment by flexgrip** [comment]
Ok, I added that override to the module's constructor thingy. Now the module compiles and boots. But refuses to show the CastButton and if I try to cast manually, I get an error about `reactNativeGoogleCast.default.cast is not a function`

**Comment by flexgrip** [comment]
Sorry to keep spamming this thread. Wonder if you've tried the commits from his react-native-google-cast v4 repo @alfiedouglas0? Presumably, the example in there works and its running RN 0.58.

**Comment by flexgrip** [comment]
It just occurred to me. I got this library to compile on android in RN 0.60.3. But I thought it was broken because the cast button is missing. However, it's also missing in youtube. So I may need to test on a real device to see if it shows up and works. Grrr.

**Comment by alfiedouglas0** [comment]
> It just occurred to me. I got this library to compile on android in RN 0.60.3. But I thought it was broken because the cast button is missing. However, it's also missing in youtube. So I may need to test on a real device to see if it shows up and works. Grrr.

oh awesome! Did you have any luck running it on a real device? and if so how did you do it! :)

**Comment by flexgrip** [comment]
I ended up using one of those android gaming emulators for mac because they often have bridged network mode. Ran my app and yes, the chromecast button showed up and seems to work. I haven't been able to cast anything, but I'm pretty sure that's because I'm instantiating it wrong.

I have to apologize. The last time I worked on it, I spent hours just trying different things and patching holes. So I don't know exactly what it was that I did. But here's the basic idea:

1. Deleted my android directory and then pulled in a copy of one from a fresh react native app.
2. Installed react-native-video first and linked it.
3. Installed react-native-google-cast and linked it
4. Went through the README of this repo with a comb and made sure I followed every direction.
5. At this point, as you saw before, shit started failing when I tried to run the android app. I think the major issue was that it kept telling me `Native module RNGoogleCast tried to override GoogleCastModule...`. Everyone on stackoverflow was saying "You probably added your package twice in your MainApplication.java". But that wasn't the case. So I commented it out, and changed my MainActivity.java to extend the original `ReactActivity`. Then it started working.

I'm sure I'm forgetting something else I did. There was a smattering of broken stuff along the way. But a complete do-over really helped (deleting my android directory and starting with a fresh one).

At one point, I think I was editing the package from the `node_modules` directory. Not sure what I did. But I'll attach it just in case.

```
package com.someapp;

import com.facebook.react.ReactActivity;
import com.facebook.react.GoogleCastActivity;

public class MainActivity extends ReactActivity {

    /**
     * Returns the name of the main component registered from JavaScript.
     * This is used to schedule rendering of the component.
     */
    @Override
    protected String getMainComponentName() {
        return "someapp";
    }

}
```

```
public class MainApplication extends Application implements ReactApplication {

  private final ReactNativeHost mReactNativeHost = new ReactNativeHost(this) {
    @Override
    public boolean getUseDeveloperSupport() {
      return BuildConfig.DEBUG;
    }

    @Override
    protected List<ReactPackage> getPackages() {
      @SuppressWarnings("UnnecessaryLocalVariable")
      List<ReactPackage> packages = new PackageList(this).getPackages();
      // Packages that cannot be autolinked yet can be added manually here, for example:
      // packages.add(new MyReactNativePackage());

      packages.add(new ReactVideoPackage());
      //packages.add(new GoogleCastPackage());
      return packages;
    }
```

[react-native-google-cast.zip](https://github.com/react-native-google-cast/react-native-google-cast/files/3408669/react-native-google-cast.zip)

**Comment by igor-nm** [comment]
Any news? I've same error here!!
And react-native's upgrade is necessary on my project

**Comment by flexgrip** [comment]
> Any news? I've same error here!!
> And react-native's upgrade is necessary on my project

It's working for me. I kinda have to rebuild my entire android directory. One thing I noticed is that I did not have to add `packages.add(new ReactVideoPackage());` or `public class MainActivity extends GoogleCastActivity`. That got my app to boot with chromecast and it worked.

That being said I haven't tested it on a real device yet.

**Comment by petrbela** [comment]
Hi everyone! I've finally found time to look at this today. There's indeed a bunch of changes due to AndroidX. I'm following the official upgrade guides and should have a fix for 0.60 available in a few hours.

**Comment by petrbela** [comment]
Btw anyone tried to use [jetifier](https://github.com/mikehardy/jetifier)?

**Comment by flexgrip** [comment]
> Btw anyone tried to use [jetifier](https://github.com/mikehardy/jetifier)?

Yep. My app (which I believe has working android chromecast) is using it.

**Comment by flexgrip** [comment]
I just noticed that on android, the icon isn't showing up when I put it in the header. However, the button is there. Because if I click where it is supposed to be, the cast dialogue shows up and lets me cast the video.

Also, regarding jetifier. I did end up having to run the jetifier update thingy and that helped.

**Comment by flexgrip** [comment]
Any update here? I'm going to try rebuilding the package from scratch again, starting with jetifier. But if you have a branch or commit almost ready, I'll wait.

**Comment by petrbela** [comment]
Not finished yet. I'll probably end up officially supporting v3 at 0.59, which could be used with a 0.60 project by using jetifier, and focus on fully migrating to 0.60 in v4 (which now gets trickier because the packages I use for the examples there haven't been migrated to 0.60 yet 😂).

**Comment by flexgrip** [comment]
@petrbela - So I started from scratch today. Reinstalled your package, set it up via the instructions, and then I ran `npx jetifier`. At that point everything compiled and ran in my apk...

The only problem is, no chromecast button :/

**Comment by flexgrip** [comment]
Actually, it does *kind of* work.

Here's what I have to do.

1. Open up youtube and click the cast button
2. Switch back to my app and click where the chromecast button *should* be and the menu opens. And it actually casts the video :)

So I think there's some problem with the logic on android where it only shows the cast button when there are devices detected. Something is causing them to not be detected when my component mounts. But if I have youtube refresh the list, your button can then cast.

Any ideas?

**Comment by flexgrip** [comment]
Grrr... Nevermind. It is showing the cast button... It's just showing up black on a black background and I can't change the damned color :)

**Comment by flexgrip** [comment]
Ok, with that settled, I am now back to a working state on android. Casting button shows up, works, etc. I still think that it's the last cast button that will show up on the list. In other words, it seems to be very delayed in finding devices to cast to...

But anyway, the only other problem I'm having is that if I stop casting from the expanded controls, it doesn't fire the SESSION_ENDED event.

**Comment by jedashford** [comment]
Just to chime in here, we upgraded to .60.5 without issue. We just left the dependency linked and jetifier ran without issue and we never had a second thought. We are getting a crash mentioned here (https://github.com/react-native-google-cast/react-native-google-cast/issues/139) which we're digging into right now: "GoogleCast.launchExpandedControls() Crashes the App #139" -

**Comment by petrbela** [comment]
Closing this, you should be able to get v3 to work with 0.60+ (and v4 with 0.59) using jetifier.
