### ISSUE TITLE
showIntroductoryOverlay error on Android

### ISSUE THREAD

**Issue by syngi** [react-native-google-cast/react-native-google-cast#200]
`GoogleCast.showIntroductoryOverlay()` throws error `TypeError: _reactNativeGoogleCast.default.showIntroductoryOverlay is not a function.` in Android, while iOS works fine (though seems to show overlay also when no Chromecasts are in range, thus when the button is not rendered).

**Versions:**
- RNGC Library Version: 3.3.0
- React: 16.11.0
- React Native: 0.62.2

**To Reproduce**
1. Install and setup as described on https://github.com/react-native-google-cast/react-native-google-cast#getting-started
2. Then in react native add
    - `import GoogleCast, { CastButton } from 'react-native-google-cast'`
    - `GoogleCast.showIntroductoryOverlay();`
        for example like:
        ```
      useEffect(() => {
          GoogleCast.showIntroductoryOverlay();
      }, []);
        ```

This will show the error instead of the overlay.

**Comment by loria33** [comment]
Hi did you resolve this I have the same problem

**Comment by syngi** [comment]
no, I just check with `if (GoogleCast.showIntroductoryOverlay)` for now.

**Comment by markymc** [comment]
Hmm... I just found this too. Surprised it's not been reported more, unless I've missed a setup step?

**Comment by markymc** [comment]
Ah, looks like it's working in v4.0.0. I could remove the `if` check.

**Comment by petrbela** [comment]
Forgot to update this. There might be some slight changes later but as far as this issue is concerned, it's fixed in v4.
